name: khm-playcanvas
services:

# Development build of the application
  pc-dev:
    build:
      context: .
      dockerfile: ${PC_DOCKERFILE}
      target: development
    volumes:
      - ./app/src/:/app/src/
      - ./app/lib/:/app/lib/
      - ./app/plugins/:/app/plugins/
      - ./app/static/:/app/static/
      - ./app/start.sh:/app/start.sh
    container_name: pc-dev
    restart: unless-stopped
    ports:
      - ${PC_DEV_PORT}:3000
    command: [sh, '-c', '/app/start.sh']
    env_file: ./.env-dev
    networks:
      - pc-local
# Production build of the application
  pc-prod:
    build:
      context: .
      dockerfile: ${PC_DOCKERFILE}
      target: production
    container_name: pc-prod
    restart: unless-stopped
    ports:
      - ${PC_PROD_PORT}:80
    command: [nginx, '-g', 'daemon off;']
    env_file: ./.env-prod
    networks:
      - pc-local
networks:
  pc-local:
    name: pc-local
    driver: bridge
